name: Labels Sync
on:
  push:
    paths:
      - .github/labels/**.yml
      - .github/workflows/labels-sync.yaml

jobs:
  tekton-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
        run: |
          echo "> Creating config (${{ github.job }}.yaml)..."
          cat .github/labels/common.yaml >> ${{ github.job }}.yaml
          cat .github/labels/type.yaml >> ${{ github.job }}.yaml
          cat .github/labels/status.yaml >> ${{ github.job }}.yaml
          echo "> Created config:"
          cat ${{ github.job }}.yaml
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: ${{ github.job }}.yaml
          repository: buildpacks/tekton-integration
          token: ${{ secrets.LEARNING_GITHUB_TOKEN }}