name: Labels Sync
on:
  push:
    branches:
      - main
    paths:
      - .github/labels/**.yml
      - .github/workflows/labels-sync.yaml

jobs:
  tekton-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:
        run: |
          echo "> Creating config (${{ github.job }}.yaml)..."
          cat .github/labels/common.yaml >> ${{ github.job }}.yaml
          cat .github/labels/type.yaml >> ${{ github.job }}.yaml
          cat .github/labels/status.yaml >> ${{ github.job }}.yaml
          cat .github/labels/k8s-platforms.yaml >> ${{ github.job }}.yaml
          echo "> Created config:"
          cat ${{ github.job }}.yaml
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: ${{ github.job }}.yaml
          repository: buildpacks/tekton-integration
          token: ${{ secrets.LEARNING_GITHUB_TOKEN }}
          prune: true # ! NOTE ! - default is true which deletes labels not in manifest
  roadmap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - buildpacks/docs
          - buildpacks/pack
    steps:
      - uses: actions/checkout@v2
      - name:
        run: |
          echo "> Creating config (${{ github.job }}.yaml)..."
          cat .github/labels/roadmap.yaml >> ${{ github.job }}.yaml
          echo "> Created config:"
          cat ${{ github.job }}.yaml
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: ${{ github.job }}.yaml
          repository: ${{ matrix.repo }}
          token: ${{ secrets.LEARNING_GITHUB_TOKEN }}
          prune: false # ! NOTE ! - default is true which deletes labels not in manifest